services:
  api_host: "nomad.nanolab.dtu.dk"
  api_base_path: "/nomad-oasis"
  upload_limit: 1000
  upload_members_group_search_enabled: true
  console_log_level: 10

oasis:
  is_oasis: true
  uses_central_user_management: true

auth:
  require_authentication: false
  reject_unauthorized_users: false
  unauthenticated_user_scopes:
    include:
      - "*:read"
  unauthorized_user_scopes:
    include:
      - "*:read"
  authorized_users:
    - 'alba'
    - 'anatitzhak'
    - 'ancro@dtu.dk'
    - 'clarabmoller'
    - 'david.miles_skov'
    - 'dtu_nanolab'
    - 'eugbe'
    - 'finta'
    - 'hampusnasstrom'
    - 'indiogo'
    - 'lena'
    - 'sanz'
    - 'sarthakdevelop3'
    - 'chmode'

client:
  url: http://nomad.nanolab.dtu.dk/nomad-oasis/api

meta:
  deployment: "oasis"
  deployment_url: http://nomad.nanolab.dtu.dk/nomad-oasis/api
  maintainer_email: "me@my-oasis.org"

logstash:
  enabled: false

temporal:
  enabled: true

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1

plugins:
  entry_points:
    exclude:
      - apps/3_experiment/2_eels
      - nomad_measurements.xrd:parser_entry_point
      - nomad_analysis.jupyter:schema_entry_point
    options:
      nomad_dtu_nanolab_plugin.schema_packages:sputtering:
        overwrite_libraries: true
      nomad_north_jupyter.north_tools:jupyter:
        north_tool:
          image: ghcr.io/dtu-nanolab-materials-discovery/nomad-oasis-image/jupyter:main
